service: pi-blog-strapi-staging

image: ghcr.io/pageinteract/pi-blog-strapi-staging

registry:
  server: ghcr.io
  username: sulmanweb
  password:
    - KAMAL_REGISTRY_PASSWORD

servers:
  strapi:
    - 65.109.162.158

primary_role: strapi

proxy:
  ssl: true
  host: stg-strapi.pageinteract.com

env:
  clear:
    NODE_ENV: production
    HOST: "0.0.0.0"
    PORT: 1337
    DATABASE_CLIENT: sqlite
    DATABASE_FILENAME: /opt/app/data/data.db
  secret:
    - ADMIN_JWT_SECRET
    - API_TOKEN_SALT
    - TRANSFER_TOKEN_SALT
    - APP_KEYS
    - JWT_SECRET
    - CLIENT_URL
    - PREVIEW_SECRET
    - RESEND_API_KEY

builder:
  dockerfile: Dockerfile
  context: .
  arch: amd64

volumes:
  - pi_blog_uploads:/opt/app/public/uploads
  - pi_blog_data:/opt/app/data

aliases:
  console: app exec --interactive --reuse "bash"
  logs: app logs -f
  strapi-console: app exec --interactive --reuse "yarn strapi console"
