service: pi-blog-staging

registry:
  server: ghcr.io
  username: sulmanweb
  password:
    - KAMAL_REGISTRY_PASSWORD

servers:
  web:
    - 65.109.162.158

proxy:
  ssl: true
  host: stg-ruby.pageinteract.com

builder:
  arch: amd64

# Next.js service configuration
services:
  nextjs:
    image: ghcr.io/pageinteract/pi-blog-nextjs-staging
    dockerfile: next/Dockerfile
    context: next
    port: 3000
    proxy:
      ssl: true
      host: stg-ruby.pageinteract.com
      path: /blog
    env:
      clear:
        NODE_ENV: production
        PORT: 3000
        HOSTNAME: "0.0.0.0"
        NEXT_TELEMETRY_DISABLED: 1
      secret:
        - NEXT_PUBLIC_API_URL
        - PREVIEW_SECRET
        - IMAGE_HOSTNAME
    volumes:
      - /tmp/nextjs-cache:/app/.next/cache

  strapi:
    image: ghcr.io/pageinteract/pi-blog-strapi-staging
    dockerfile: strapi/Dockerfile
    context: strapi
    port: 1337
    proxy:
      ssl: true
      host: stg-strapi.pageinteract.com
    env:
      clear:
        NODE_ENV: production
        HOST: "0.0.0.0"
        PORT: 1337
        DATABASE_CLIENT: postgres
        DATABASE_HOST: pi-blog-staging-postgres
        DATABASE_PORT: 5432
        DATABASE_NAME: pi_blog_stg
        DATABASE_USERNAME: postgres
        DATABASE_SCHEMA: public
        DATABASE_SSL: false
      secret:
        - DATABASE_PASSWORD
        - ADMIN_JWT_SECRET
        - API_TOKEN_SALT
        - TRANSFER_TOKEN_SALT
        - APP_KEYS
        - JWT_SECRET
        - CLIENT_URL
        - PREVIEW_SECRET
        - RESEND_API_KEY
    volumes:
      - pi_blog_uploads:/opt/app/public/uploads

accessories:
  postgres:
    image: postgres:17-alpine
    host: 65.109.162.158
    port: 5432
    cmd: postgres -c max_connections=50
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: pi_blog_stg
        POSTGRES_INITDB_ARGS: ""
      secret:
        - DATABASE_PASSWORD
    volumes:
      - /var/lib/postgresql/pi_blog_staging:/var/lib/postgresql/data

  postgres_backup:
    image: kartoza/pg-backup:17-3.5
    host: 65.109.162.158
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: pi_blog_stg
        POSTGRES_HOST: pi-blog-staging-postgres
        POSTGRES_PORT: 5432
        CRON_SCHEDULE: "0 2 * * 0" # Weekly backups on Sunday at 2am
      secret:
        - DATABASE_PASSWORD
    directories:
      - backups:/backups

aliases:
  console: app exec --interactive --reuse "bash"
  logs: app logs -f
  strapi-console: strapi exec --interactive --reuse "yarn strapi console"
  nextjs-logs: nextjs logs -f
  strapi-logs: strapi logs -f