service: pi-blog-nextjs-staging

image: ghcr.io/pageinteract/pi-blog-nextjs-staging

registry:
  server: ghcr.io
  username: sulmanweb
  password: KAMAL_REGISTRY_PASSWORD

servers:
  web:
    - 65.109.162.158

proxy:
  ssl: true
  host: stg-ruby.pageinteract.com
  path_prefix: "/blog"

env:
  clear:
    NODE_ENV: production
    PORT: 3000
    HOSTNAME: "0.0.0.0"
    NEXT_TELEMETRY_DISABLED: 1
  secret:
    - NEXT_PUBLIC_API_URL
    - PREVIEW_SECRET
    - IMAGE_HOSTNAME

builder:
  dockerfile: next/Dockerfile
  context: next
  arch: amd64

volumes:
  - /tmp/nextjs-cache:/app/.next/cache

aliases:
  console: app exec --interactive --reuse "bash"
  logs: app logs -f