name: Deploy to Staging

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false

    - name: Install Kamal
      run: gem install kamal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create environment file
      run: |
        cat > .env << EOF
        KAMAL_REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }}
        ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
        API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
        TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}
        APP_KEYS=${{ secrets.APP_KEYS }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        NEXT_PUBLIC_API_URL=https://stg-strapi.pageinteract.com
        CLIENT_URL=https://stg-ruby.pageinteract.com
        PREVIEW_SECRET=${{ secrets.PREVIEW_SECRET }}
        IMAGE_HOSTNAME=stg-strapi.pageinteract.com
        RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
        EOF

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H 65.109.162.158 >> ~/.ssh/known_hosts

    - name: Deploy Next.js to staging
      run: |
        kamal deploy -c config/deploy.staging.yml

    - name: Deploy Strapi to staging
      run: |
        kamal deploy -c config/deploy.strapi.staging.yml

    - name: Health check
      run: |
        sleep 30
        curl -f https://stg-ruby.pageinteract.com/blog || exit 1
        curl -f https://stg-strapi.pageinteract.com/api/articles || exit 1

    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Staging deployment successful!"
          echo "Blog: https://stg-ruby.pageinteract.com/blog"
          echo "Admin: https://stg-strapi.pageinteract.com/admin"
        else
          echo "❌ Staging deployment failed!"
        fi